version: '2.2'
services:
  redis:
    image: 'redis:latest'
    command: redis-server --requirepass redispass

  mysql:
    image: mysql:5.7.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./configs/mysql:/etc/mysql

  webserver:
    image: malidong/docker-airflow:latest
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
      - REDIS_PASSWORD=redispass
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: malidong/docker-airflow:latest
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: malidong/docker-airflow:latest
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DB=airflow
      - REDIS_PASSWORD=redispass
    command: scheduler

  worker:
    image: malidong/docker-airflow:latest
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DB=airflow
      - REDIS_PASSWORD=redispass
    command: worker
